apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::030796672830:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-GiASLrvYbuek
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn:  arn:aws:iam::030796672830:user/suresh
      username: suresh
    - groups:
      - roboshop-admin  
      userarn:  arn:aws:iam::030796672830:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T15:22:34Z"
  name: aws-auth
  namespace: kube-system
  uid: 8cdb228e-0fbb-45fe-9ec1-3132bf1ed8ae